# Generated by Django 2.2.16 on 2022-09-15 15:20

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220912_1346'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(
                fields=('user', 'following'),
                name='unique_follow'
            ),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(
                check=models.Q(
                    _negated=True,
                    user=django.db.models.expressions.F('following')
                ),
                name='prevent_self_follow'
            ),
        ),
    ]
